---
- name: Install dependencies for building Python
  yum:
    name:
      - gcc
      - openssl-devel
      - bzip2-devel
      - libffi-devel
      - wget
      - make
    state: present

- name: Download Python 3.8 source
  get_url:
    url: https://www.python.org/ftp/python/3.8.18/Python-3.8.18.tgz
    dest: /tmp/Python-3.8.18.tgz

- name: Extract Python source
  unarchive:
    src: /tmp/Python-3.8.18.tgz
    dest: /tmp
    remote_src: yes

- name: Compile and install Python 3.8
  shell: |
    cd /tmp/Python-3.8.18
    ./configure --enable-optimizations
    make altinstall
  args:
    creates: /usr/local/bin/python3.8

- name: Set python3.8 as the default interpreter for Ansible
  lineinfile:
    path: /etc/profile
    line: 'export PATH=/usr/local/bin:$PATH'
    state: present
