---
- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Install required packages
  yum:
    name:
      - java-17-amazon-corretto
      - git
      - maven
    state: present

- name: Copy Spring Boot application JAR
  copy:
    src: ecommerce-1.0.0.jar
    dest: /home/ec2-user/ecommerce.jar
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Create systemd service for Spring Boot app
  copy:
    dest: /etc/systemd/system/ecommerce.service
    content: |
      [Unit]
      Description=Spring Boot Application
      After=network.target

      [Service]
      User=ec2-user
      ExecStart=/usr/bin/java -jar /home/ec2-user/ecommerce.jar
      SuccessExitStatus=143
      Restart=always
      RestartSec=5

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable and start ecommerce app
  systemd:
    name: ecommerce
    enabled: true
    state: started

- name: Wait for app to respond
  wait_for:
    port: 8080
    delay: 10
    timeout: 60
    state: started

- name: Check app health
  uri:
    url: http://localhost:8080/actuator/health
    return_content: yes
  register: springboot_health
  failed_when: "'UP' not in springboot_health.content"
  changed_when: false

- name: Display health check result
  debug:
    msg: "Spring Boot app health: {{ springboot_health.content }}"
