---
- name: Download Amazon Corretto 21 RPM
  get_url:
    url: https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm
    dest: /tmp/amazon-corretto-21.rpm

- name: Install Amazon Corretto 21 RPM using rpm command (tolerate already-installed)
  command: rpm -ivh /tmp/amazon-corretto-21.rpm
  register: rpm_result
  ignore_errors: true

- name: Fail if rpm really failed (not just already installed)
  fail:
    msg: "RPM installation failed for Corretto 21"
  when: rpm_result.rc != 0 and
        rpm_result.stderr_lines is defined and
        not rpm_result.stderr_lines | join(' ') is search("is already installed")






- name: Clean up Amazon Corretto RPM file
  file:
    path: /tmp/amazon-corretto-21.rpm
    state: absent

- name: Install required packages using shell (yum fallback)
  shell: yum install -y git docker


- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Create .ssh directory
  file:
    path: /home/ec2-user/.ssh
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0700'

- name: Copy Jenkins controller public key to agent
  copy:
    src: id_rsa.pub
    dest: /home/ec2-user/.ssh/authorized_keys
    owner: ec2-user
    group: ec2-user
    mode: '0600'

- name: Set JAVA_HOME
  lineinfile:
    path: /etc/profile.d/java.sh
    line: 'export JAVA_HOME=/usr/lib/jvm/amazon-corretto-21'
    create: yes

